#pragma once

#define DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES

#include <doctest/doctest.h>

#define IMPLEMENTATION_BEGIN_SUITE(name) DOCTEST_TEST_SUITE_BEGIN (#name);

#define IMPLEMENTATION_END_SUITE DOCTEST_TEST_SUITE_END;

#define IMPLEMENTATION_TEST_CASE(name) DOCTEST_TEST_CASE (#name)

#define IMPLEMENTATION_CHECK(...) DOCTEST_CHECK (__VA_ARGS__)

#define IMPLEMENTATION_REQUIRE(...) DOCTEST_REQUIRE (__VA_ARGS__)

#define IMPLEMENTATION_CHECK_EQUAL(...) DOCTEST_CHECK_EQ (__VA_ARGS__)

#define IMPLEMENTATION_REQUIRE_EQUAL(...) DOCTEST_REQUIRE_EQ (__VA_ARGS__)

#define IMPLEMENTATION_CHECK_WITH_MESSAGE(...) DOCTEST_CHECK_MESSAGE (__VA_ARGS__)

#define IMPLEMENTATION_REQUIRE_WITH_MESSAGE(...) DOCTEST_REQUIRE_MESSAGE (__VA_ARGS__)

#define IMPLEMENTATION_LOG(...) DOCTEST_MESSAGE (__VA_ARGS__)