#pragma once

#define DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES

#include <doctest/doctest.h>

#define IMPLEMENTATION_TEST_CASE(name) DOCTEST_TEST_CASE (#name)

#define IMPLEMENTATION_BEGIN_SUITE(name) DOCTEST_TEST_SUITE_BEGIN (#name);

#define IMPLEMENTATION_END_SUITE DOCTEST_TEST_SUITE_END;

#define IMPLEMENTATION_CHECK(...) DOCTEST_CHECK (__VA_ARGS__)

#define IMPLEMENTATION_REQUIRE(...) DOCTEST_REQUIRE (__VA_ARGS__)

#define IMPLEMENTATION_INFO(...) DOCTEST_INFO (__VA_ARGS__)