# PathMapping
configs:
  - typeName: CharacterAnimationConfiguration
    folder: CharacterAnimationConfigurations
  - typeName: DynamicsMaterial2d
    folder: DynamicsMaterials
  - typeName: MovementConfiguration
    folder: MovementConfigurations
