# After repository checkout we must download binary dependencies either from cache or network.
# This behaviour is shared between all workflows using this composite action.
name: 'Checkout with dependencies'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ./Dependency
        key: ${{runner.os}}-dependencies

    - name: Setup dependencies
      run: |
        .\Script\Dependency\OGRE.ps1 ${{runner.os}}
        echo "OGRE_DIR=${{github.workspace}}\Dependency\OGRE\${{runner.os}}" >> $Env:GITHUB_ENV
