name: 'Setup dependencies'
description: "Downloads binary dependencies either from cache or network."
inputs:
  platform:
    description: 'Target platform for dependency binaries.'
    required: true
  build_type:
    description: 'Dependency binaries build type.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ./Dependency
        # We use "-version-[0-9]+" suffix to drop cache when we are updating dependencies.
        # Unfortunately, there is no better way to drop old cache from GitHub Actions right now.
        key: ${{inputs.platform}}-${{inputs.build_type}}-dependencies-version-1

    - name: Setup dependencies
      shell: pwsh
      run: |
        .\Script\Dependency\Download.ps1 ${{inputs.platform}} ${{inputs.build_type}}
        echo "URHO3D_DIR=${{github.workspace}}\Dependency\Urho3D\${{inputs.platform}}\${{inputs.build_type}}" >> $Env:GITHUB_ENV
        echo "PHYSX_DIR=${{github.workspace}}\Dependency\PhysX\${{inputs.platform}}\${{inputs.build_type}}" >> $Env:GITHUB_ENV
