# Downloads binary dependencies either from cache or network.
name: 'Setup dependencies'
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ./Dependency
        key: ${{runner.os}}-dependencies

    - name: Setup dependencies
      shell: pwsh
      run: |
        .\Script\Dependency\Urho3D.ps1 ${{runner.os}}
        echo "URHO3D_DIR=${{github.workspace}}\Dependency\Urho3D\${{runner.os}}" >> $Env:GITHUB_ENV
