#include <Warehouse/Test/VisualizationGraphs.hpp>
#include <Warehouse/Visualization.hpp>

namespace Emergence::Warehouse::Test
{
using namespace VisualGraph::Common::Constants;

static std::string MappingPath ()
{
    return std::string (DEFAULT_ROOT_GRAPH_ID) + VisualGraph::NODE_PATH_SEPARATOR + MAPPING_SUBGRAPH +
           VisualGraph::NODE_PATH_SEPARATOR;
}

static std::string RegistryPath ()
{
    return std::string (DEFAULT_ROOT_GRAPH_ID) + VisualGraph::NODE_PATH_SEPARATOR + WAREHOUSE_REGISTRY_SUBGRAPH +
           VisualGraph::NODE_PATH_SEPARATOR;
}

VisualizationExpectedResult Graphs::OneQueryForEachCombination ()
{
    return {{"Test",
             {},
             {{"SingletonContainer {BoundingBox}",
               {},
               {},
               {{".", {}}},
               {{".", MappingPath () + "BoundingBox/.", MAPPING_USAGE_COLOR}}},
              {"ShortTermContainer {Player}",
               {},
               {},
               {{".", {}}},
               {{".", MappingPath () + "Player/.", MAPPING_USAGE_COLOR}}},
              {"LongTermContainer {PlayerWithBoundingBox}",
               {},
               {{"RecordCollection {PlayerWithBoundingBox}",
                 {},
                 {{"LinearRepresentation {player.id}",
                   {},
                   {},
                   {{RECORD_COLLECTION_REPRESENTATION_ROOT_NODE, {}}},
                   {{RECORD_COLLECTION_REPRESENTATION_ROOT_NODE, MappingPath () + "PlayerWithBoundingBox/player.id",
                     MAPPING_USAGE_COLOR}}}},
                 {{RECORD_COLLECTION_ROOT_NODE, {}}},
                 {{RECORD_COLLECTION_ROOT_NODE, MappingPath () + "PlayerWithBoundingBox/.", MAPPING_USAGE_COLOR},
                  {RECORD_COLLECTION_ROOT_NODE, "LinearRepresentation {player.id}/.", {}}}}},
               {{".", {}}},
               {{".", MappingPath () + "PlayerWithBoundingBox/.", MAPPING_USAGE_COLOR}}}},
             {{WAREHOUSE_REGISTRY_ROOT_NODE, {}}},
             {}},
            {{"FetchAscendingRangeQuery {PlayerWithBoundingBox: player.id}",
              {},
              {},
              {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
              {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "PlayerWithBoundingBox/.", MAPPING_USAGE_COLOR},
               {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/LongTermContainer {PlayerWithBoundingBox}/.", {}},
               {WAREHOUSE_QUERY_ROOT_NODE,
                RegistryPath () + "Test/LongTermContainer {PlayerWithBoundingBox}/RecordCollection "
                                  "{PlayerWithBoundingBox}/LinearRepresentation {player.id}/.",
                {}},
               {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "PlayerWithBoundingBox/player.id", MAPPING_USAGE_COLOR}}},
             {"FetchSequenceQuery {Player}",
              {},
              {},
              {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
              {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/.", MAPPING_USAGE_COLOR},
               {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/ShortTermContainer {Player}/.", {}}}},
             {"FetchSingletonQuery {BoundingBox}",
              {},
              {},
              {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
              {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/.", MAPPING_USAGE_COLOR},
               {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/SingletonContainer {BoundingBox}/.", {}}}}}};
}

VisualizationExpectedResult Graphs::Singletons ()
{
    return {{"Test",
             {},
             {{"SingletonContainer {Player}",
               {},
               {},
               {{".", {}}},
               {{".", MappingPath () + "Player/.", MAPPING_USAGE_COLOR}}},
              {"SingletonContainer {BoundingBox}",
               {},
               {},
               {{".", {}}},
               {{".", MappingPath () + "BoundingBox/.", MAPPING_USAGE_COLOR}}}},
             {{WAREHOUSE_REGISTRY_ROOT_NODE, {}}},
             {}},
            {{"FetchSingletonQuery {Player}",
              {},
              {},
              {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
              {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/.", MAPPING_USAGE_COLOR},
               {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/SingletonContainer {Player}/.", {}}}},
             {"ModifySingletonQuery {BoundingBox}",
              {},
              {},
              {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
              {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/.", MAPPING_USAGE_COLOR},
               {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/SingletonContainer {BoundingBox}/.", {}}}}}};
}

VisualizationExpectedResult Graphs::Sequences ()
{
    return {{"Test",
             {},
             {{"ShortTermContainer {Player}",
               {},
               {},
               {{".", {}}},
               {{".", MappingPath () + "Player/.", MAPPING_USAGE_COLOR}}},
              {"ShortTermContainer {BoundingBox}",
               {},
               {},
               {{".", {}}},
               {{".", MappingPath () + "BoundingBox/.", MAPPING_USAGE_COLOR}}}},
             {{WAREHOUSE_REGISTRY_ROOT_NODE, {}}},
             {}},
            {{"FetchSequenceQuery {Player}",
              {},
              {},
              {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
              {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/.", MAPPING_USAGE_COLOR},
               {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/ShortTermContainer {Player}/.", {}}}},
             {"InsertShortTermQuery {Player}",
              {},
              {},
              {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
              {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/.", MAPPING_USAGE_COLOR},
               {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/ShortTermContainer {Player}/.", {}}}},
             {"ModifySequenceQuery {BoundingBox}",
              {},
              {},
              {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
              {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/.", MAPPING_USAGE_COLOR},
               {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/ShortTermContainer {BoundingBox}/.", {}}}}}};
}

VisualizationExpectedResult Graphs::LongTerms ()
{
    return {
        {"Test",
         {},
         {{"LongTermContainer {Player}",
           {},
           {{"RecordCollection {Player}",
             {},
             {{"LinearRepresentation {id}",
               {},
               {},
               {{".", {}}},
               {{".", MappingPath () + "Player/id", MAPPING_USAGE_COLOR}}},
              {"LinearRepresentation {name}",
               {},
               {},
               {{RECORD_COLLECTION_REPRESENTATION_ROOT_NODE, {}}},
               {{RECORD_COLLECTION_REPRESENTATION_ROOT_NODE, MappingPath () + "Player/name", MAPPING_USAGE_COLOR}}},
              {"PointRepresentation {alive}",
               {},
               {},
               {{RECORD_COLLECTION_REPRESENTATION_ROOT_NODE, {}}},
               {{RECORD_COLLECTION_REPRESENTATION_ROOT_NODE, MappingPath () + "Player/alive", MAPPING_USAGE_COLOR}}}},
             {{RECORD_COLLECTION_ROOT_NODE, {}}},
             {{RECORD_COLLECTION_ROOT_NODE, MappingPath () + "Player/.", MAPPING_USAGE_COLOR},
              {RECORD_COLLECTION_ROOT_NODE, "LinearRepresentation {id}/.", {}},
              {RECORD_COLLECTION_ROOT_NODE, "LinearRepresentation {name}/.", {}},
              {RECORD_COLLECTION_ROOT_NODE, "PointRepresentation {alive}/.", {}}}}},
           {{".", {}}},
           {{".", MappingPath () + "Player/.", MAPPING_USAGE_COLOR}}},
          {"LongTermContainer {BoundingBox}",
           {},
           {{"RecordCollection {BoundingBox}",
             {},
             {{"VolumetricRepresentation {{minX, maxX}, {minY, maxY}, {minZ, maxZ}}",
               {},
               {},
               {{RECORD_COLLECTION_REPRESENTATION_ROOT_NODE, {}}},
               {{RECORD_COLLECTION_REPRESENTATION_ROOT_NODE, MappingPath () + "BoundingBox/minX", MAPPING_USAGE_COLOR},
                {RECORD_COLLECTION_REPRESENTATION_ROOT_NODE, MappingPath () + "BoundingBox/maxX", MAPPING_USAGE_COLOR},
                {RECORD_COLLECTION_REPRESENTATION_ROOT_NODE, MappingPath () + "BoundingBox/minY", MAPPING_USAGE_COLOR},
                {RECORD_COLLECTION_REPRESENTATION_ROOT_NODE, MappingPath () + "BoundingBox/maxY", MAPPING_USAGE_COLOR},
                {RECORD_COLLECTION_REPRESENTATION_ROOT_NODE, MappingPath () + "BoundingBox/minZ", MAPPING_USAGE_COLOR},
                {RECORD_COLLECTION_REPRESENTATION_ROOT_NODE, MappingPath () + "BoundingBox/maxZ",
                 MAPPING_USAGE_COLOR}}}},
             {{RECORD_COLLECTION_ROOT_NODE, {}}},
             {{RECORD_COLLECTION_ROOT_NODE, MappingPath () + "BoundingBox/.", MAPPING_USAGE_COLOR},
              {RECORD_COLLECTION_ROOT_NODE,
               "VolumetricRepresentation {{minX, maxX}, {minY, maxY}, {minZ, maxZ}}/.",
               {}}}}},
           {{".", {}}},
           {{".", MappingPath () + "BoundingBox/.", MAPPING_USAGE_COLOR}}}},
         {{WAREHOUSE_REGISTRY_ROOT_NODE, {}}},
         {}},
        {{"FetchAscendingRangeQuery {Player: id}",
          {},
          {},
          {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
          {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/.", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/LongTermContainer {Player}/.", {}},
           {WAREHOUSE_QUERY_ROOT_NODE,
            RegistryPath () + "Test/LongTermContainer {Player}/RecordCollection {Player}/LinearRepresentation {id}/.",
            {}},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/id", MAPPING_USAGE_COLOR}}},
         {"FetchDescendingRangeQuery {Player: name}",
          {},
          {},
          {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
          {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/.", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/LongTermContainer {Player}/.", {}},
           {WAREHOUSE_QUERY_ROOT_NODE,
            RegistryPath () + "Test/LongTermContainer {Player}/RecordCollection {Player}/LinearRepresentation {name}/.",
            {}},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/name", MAPPING_USAGE_COLOR}}},
         {"FetchRayIntersectionQuery {BoundingBox: {minX, maxX}, {minY, maxY}, {minZ, maxZ}}",
          {},
          {},
          {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
          {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/.", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/LongTermContainer {BoundingBox}/.", {}},
           {WAREHOUSE_QUERY_ROOT_NODE,
            RegistryPath () + "Test/LongTermContainer {BoundingBox}/RecordCollection "
                              "{BoundingBox}/VolumetricRepresentation {{minX, maxX}, {minY, maxY}, {minZ, maxZ}}/.",
            {}},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/minX", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/maxX", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/minY", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/maxY", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/minZ", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/maxZ", MAPPING_USAGE_COLOR}}},
         {"FetchShapeIntersectionQuery {BoundingBox: {minX, maxX}, {minY, maxY}, {minZ, maxZ}}",
          {},
          {},
          {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
          {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/.", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/LongTermContainer {BoundingBox}/.", {}},
           {WAREHOUSE_QUERY_ROOT_NODE,
            RegistryPath () + "Test/LongTermContainer {BoundingBox}/RecordCollection "
                              "{BoundingBox}/VolumetricRepresentation {{minX, maxX}, {minY, maxY}, {minZ, maxZ}}/.",
            {}},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/minX", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/maxX", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/minY", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/maxY", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/minZ", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/maxZ", MAPPING_USAGE_COLOR}}},
         {"FetchValueQuery {Player: alive}",
          {},
          {},
          {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
          {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/.", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/LongTermContainer {Player}/.", {}},
           {WAREHOUSE_QUERY_ROOT_NODE,
            RegistryPath () + "Test/LongTermContainer {Player}/RecordCollection {Player}/PointRepresentation {alive}/.",
            {}},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/alive", MAPPING_USAGE_COLOR}}},
         {"InsertLongTermQuery {Player}",
          {},
          {},
          {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
          {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/.", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/LongTermContainer {Player}/.", {}}}},
         {"ModifyAscendingRangeQuery {Player: id}",
          {},
          {},
          {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
          {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/.", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/LongTermContainer {Player}/.", {}},
           {WAREHOUSE_QUERY_ROOT_NODE,
            RegistryPath () + "Test/LongTermContainer {Player}/RecordCollection {Player}/LinearRepresentation {id}/.",
            {}},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/id", MAPPING_USAGE_COLOR}}},
         {"ModifyDescendingRangeQuery {Player: name}",
          {},
          {},
          {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
          {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/.", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/LongTermContainer {Player}/.", {}},
           {WAREHOUSE_QUERY_ROOT_NODE,
            RegistryPath () + "Test/LongTermContainer {Player}/RecordCollection {Player}/LinearRepresentation {name}/.",
            {}},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/name", MAPPING_USAGE_COLOR}}},
         {"ModifyRayIntersectionQuery {BoundingBox: {minX, maxX}, {minY, maxY}, {minZ, maxZ}}",
          {},
          {},
          {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
          {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/.", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/LongTermContainer {BoundingBox}/.", {}},
           {WAREHOUSE_QUERY_ROOT_NODE,
            RegistryPath () + "Test/LongTermContainer {BoundingBox}/RecordCollection "
                              "{BoundingBox}/VolumetricRepresentation {{minX, maxX}, {minY, maxY}, {minZ, maxZ}}/.",
            {}},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/minX", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/maxX", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/minY", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/maxY", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/minZ", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/maxZ", MAPPING_USAGE_COLOR}}},
         {"ModifyShapeIntersectionQuery {BoundingBox: {minX, maxX}, {minY, maxY}, {minZ, maxZ}}",
          {},
          {},
          {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
          {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/.", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/LongTermContainer {BoundingBox}/.", {}},
           {WAREHOUSE_QUERY_ROOT_NODE,
            RegistryPath () + "Test/LongTermContainer {BoundingBox}/RecordCollection "
                              "{BoundingBox}/VolumetricRepresentation {{minX, maxX}, {minY, maxY}, {minZ, maxZ}}/.",
            {}},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/minX", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/maxX", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/minY", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/maxY", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/minZ", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "BoundingBox/maxZ", MAPPING_USAGE_COLOR}}},
         {"ModifyValueQuery {Player: alive}",
          {},
          {},
          {{WAREHOUSE_QUERY_ROOT_NODE, {}}},
          {{WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/.", MAPPING_USAGE_COLOR},
           {WAREHOUSE_QUERY_ROOT_NODE, RegistryPath () + "Test/LongTermContainer {Player}/.", {}},
           {WAREHOUSE_QUERY_ROOT_NODE,
            RegistryPath () + "Test/LongTermContainer {Player}/RecordCollection {Player}/PointRepresentation {alive}/.",
            {}},
           {WAREHOUSE_QUERY_ROOT_NODE, MappingPath () + "Player/alive", MAPPING_USAGE_COLOR}}}}};
}
} // namespace Emergence::Warehouse::Test
