name: Check code style

on:
  pull_request:
    branches:
      - master

jobs:
  check_code_style:
    defaults:
      run:
        shell: pwsh

    env:
      BUILD_DIRECTORY: ${{github.workspace}}\Build
      CC: clang
      CXX: clang++

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Dependencies
        uses: ./.github/actions/SetupDependencies
        with:
          platform: ${{runner.os}}
          build_type: Debug

      # TODO: Now windows-latest is VS 2022. Try to use CLangCL again?
      - name: Install Ninja
        run: choco install ninja

      - name: Create build directory
        run: cmake -E make_directory ${{env.BUILD_DIRECTORY}}

      - name: Configure
        working-directory: ${{env.BUILD_DIRECTORY}}
        run: > 
          cmake -G Ninja ${{github.workspace}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON 
          -DCMAKE_BUILD_TYPE=Debug -DEMERGENCE_CODE_STYLE_CHECK_ADHOC=ON

      - name: Run CLang Format
        run: .\Script\CodeStyle\CheckCLangFormat.ps1

      - name: Run CLang Tidy
        run: .\Script\CodeStyle\CheckCLangTidy.ps1 ${{env.BUILD_DIRECTORY}}
