name: Check code style

on:
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    defaults:
      run:
        shell: pwsh

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Check C++ code style using CLang Format
        run: .\Script\CodeStyle\CheckCLangFormat.ps1