name: Check code style

on:
  pull_request:
    branches:
      - master

jobs:
  check_code_style:
    defaults:
      run:
        shell: pwsh

    env:
      BUILD_DIRECTORY: ${{github.workspace}}\Build

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ./Dependency
          key: ${{runner.os}}-dependencies

      - name: Setup dependencies
        run: > 
          .\Script\Dependency\OGRE.ps1 ${{runner.os}}
          echo "OGRE_DIR=${{github.workspace}}\Dependency\OGRE\${{runner.os}}" >> $Env:GITHUB_ENV

      - name: Install Ninja
        run: choco install ninja

      - name: Create build directory
        run: cmake -E make_directory ${{env.BUILD_DIRECTORY}}

      - name: Configure
        working-directory: ${{env.BUILD_DIRECTORY}}
        run: cmake -G Ninja ${{github.workspace}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Check C++ code style using CLang Tools
        working-directory: ${{github.workspace}}
        # Code style checking scripts need to call llvm toolset executables, therefore it's required to import
        # Visual Studio environment, which is currently possible only through standard command line.
        shell: cmd
        run: >
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" &&
          powershell .\Script\CodeStyle\CheckCLangFormat.ps1 &&
          powershell .\Script\CodeStyle\CheckCLangTidy.ps1 ${{env.BUILD_DIRECTORY}}
