name: Check code style

on:
  pull_request:
    branches:
      - master

jobs:
  check_code_style:
    defaults:
      run:
        shell: pwsh

    env:
      BUILD_DIRECTORY: ${{github.workspace}}\Build
      CC: clang
      CXX: clang++

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ./Dependency
          key: ${{runner.os}}-dependencies

      - name: Setup dependencies
        run: |
          .\Script\Dependency\OGRE.ps1 ${{runner.os}}
          echo "OGRE_DIR=${{github.workspace}}\Dependency\OGRE\${{runner.os}}" >> $Env:GITHUB_ENV

      - name: Install Ninja
        run: choco install ninja

      - name: Create build directory
        run: cmake -E make_directory ${{env.BUILD_DIRECTORY}}

      - name: Configure
        working-directory: ${{env.BUILD_DIRECTORY}}
        run: cmake -G "Ninja Multi-Config" ${{github.workspace}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Check C++ code style using CLang Tools
        working-directory: ${{github.workspace}}
        # We use CMD instead of PowerShell because of convenient && operator.
        shell: cmd
        run: >
          powershell .\Script\CodeStyle\CheckCLangFormat.ps1 &&
          powershell .\Script\CodeStyle\CheckCLangTidy.ps1 ${{env.BUILD_DIRECTORY}}
