name: Check code style

on:
  pull_request:
    branches:
      - master

jobs:
  check_code_style:
    defaults:
      run:
        shell: pwsh

    env:
      BUILD_DIRECTORY: ${{github.workspace}}/Build

    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install CLang Tools
        shell: bash
        run: |
          brew install llvm
          ln -s "/usr/local/opt/llvm/bin/clang-format" "/usr/local/bin/clang-format"
          ln -s "/usr/local/opt/llvm/bin/clang-tidy" "/usr/local/bin/clang-tidy"
          clang-format --version
          clang-tidy --version

      - name: Create build directory
        run: cmake -E make_directory ${{env.BUILD_DIRECTORY}}

      - name: Configure
        working-directory: ${{env.BUILD_DIRECTORY}}
        run: cmake $Env:GITHUB_WORKSPACE -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run CLang Format
        run: .\Script\CodeStyle\CheckCLangFormat.ps1

      - name: Run CLang Tidy
        run: .\Script\CodeStyle\CheckCLangTidy.ps1 "${{env.BUILD_DIRECTORY}}\compile_commands.json"
