name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    strategy:

      # TODO: Temporary
      fail-fast: false

      matrix:
        build_type: [ Release, Debug ]
        os: [ windows-latest ]
        toolchain: [ Clang, MSVC ]

    defaults:
      run:
        shell: pwsh

    env:
      BUILD_DIRECTORY: ${{github.workspace}}/Build

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create build directory
        run: cmake -E make_directory ${{env.BUILD_DIRECTORY}}

      - name: Select CLangCL toolset
        if: matrix.os == 'windows-latest' && matrix.toolchain == 'CLang'
        run: echo "TOOLSET=clangcl" >> $Env:GITHUB_ENV

      - name: Select MSVC toolset
        if: matrix.os == 'windows-latest' && matrix.toolchain == 'MSVC'
        run: echo "TOOLSET=v142" >> $Env:GITHUB_ENV

      - name: Configure
        working-directory: ${{env.BUILD_DIRECTORY}}
        run: cmake $Env:GITHUB_WORKSPACE -T $Env:TOOLSET

      - name: Build
        working-directory: ${{env.BUILD_DIRECTORY}}
        run: cmake --build . --target EmergenceTests --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{env.BUILD_DIRECTORY}}
        run: ctest -C ${{matrix.build_type}}

      - name: Upload logs
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Test logs (${{matrix.os}}, ${{matrix.toolchain}}, ${{matrix.build_type}})
          path: ${{env.BUILD_DIRECTORY}}/Testing/Temporary